-- Undo for match_june_to_may.py (SFT June 2026, budget 3).
-- Restores the deleted sections, lines and values at their original ids.
BEGIN;
INSERT INTO budget_sections (id, budget_id, name, section_type, sort_order) VALUES (23, 3, 'INTERCOMPANY INVOICES', 'expense', 4);
INSERT INTO budget_sections (id, budget_id, name, section_type, sort_order) VALUES (27, 3, 'OTHER', 'expense', 8);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (543, 20, 'Sanitech ', NULL, 9, 'auto', 'supplier:136', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (768, 543, 6, 2026, 3622.50, 0.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (546, 20, 'Polyacres', NULL, 10, 'auto', 'supplier:87', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (773, 546, 6, 2026, 46000.00, 0.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (144, 21, 'Axxess', NULL, 0, 'auto', 'supplier:43', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (185, 144, 6, 2026, 0.00, 1045.00, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (771, 144, 7, 2026, 0.00, 1045.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (145, 21, 'Kokomo', NULL, 1, 'auto', 'supplier:78', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (186, 145, 6, 2026, 0.00, 3500.00, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (417, 145, 7, 2026, 3500.00, 0.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (149, 21, 'Neasa', NULL, 2, 'auto', 'supplier:80', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (190, 149, 6, 2026, 0.00, 650.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (150, 21, 'Meliora Tech', NULL, 3, 'auto', 'supplier:159', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (191, 150, 6, 2026, 0.00, 47400.00, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (758, 150, 7, 2026, 0.00, 6024.66, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (151, 21, 'Debit orders', NULL, 4, 'auto', 'supplier:321', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (192, 151, 6, 2026, 0.00, 120459.52, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (153, 21, 'Cash - Personal', NULL, 5, 'auto', 'supplier:319', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (194, 153, 6, 2026, 434190.00, 699444.12, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (154, 21, 'Truck/Trailer (purchases)', NULL, 6, 'auto', 'supplier:372', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (195, 154, 6, 2026, 7611505.00, 0.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (162, 21, 'NC Services ', NULL, 11, 'auto', 'supplier:384', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (203, 162, 6, 2026, 0.00, 1428.67, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (163, 21, 'Daimler Truck Financial Services', NULL, 12, 'auto', 'supplier:17', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (204, 163, 6, 2026, 0.00, 95604.33, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (762, 163, 7, 2026, 0.00, 102228.93, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (170, 21, 'Silverfalls', NULL, 18, 'auto', 'supplier:310', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (211, 170, 6, 2026, 173333.76, 558286.08, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (764, 170, 7, 2026, 173333.75, 0.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (173, 21, 'Grindstone ( rental) ', NULL, 20, 'auto', 'supplier:266', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (214, 173, 6, 2026, 0.00, 19318.05, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (765, 173, 7, 2026, 0.00, 19363.01, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (174, 21, 'Obhi (Pty) Ltd', NULL, 21, 'auto', 'supplier:375', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (215, 174, 6, 2026, 0.00, 159475.79, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (175, 21, 'Thembis People', NULL, 22, 'auto', 'supplier:376', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (216, 175, 6, 2026, 0.00, 685121.54, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (766, 175, 7, 2026, 9351.24, 0.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (180, 21, 'Paterson Tyres', NULL, 27, 'auto', 'supplier:153', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (221, 180, 6, 2026, 0.00, 2490.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (544, 21, 'Cash Refunds - Saggrys', NULL, 33, 'auto', 'supplier:389', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (769, 544, 6, 2026, 0.00, 1040.00, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (770, 544, 7, 2026, 0.00, 731.40, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (548, 21, 'Pkf', NULL, 36, 'auto', 'supplier:39', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (775, 548, 6, 2026, 31970.00, 0.00, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (181, 24, '7CS', NULL, 0, 'auto', 'subcontractor:12', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (222, 181, 6, 2026, 577785.07, NULL, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (780, 181, 7, 2026, 40584.88, NULL, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (182, 24, 'Krip', NULL, 1, 'auto', 'subcontractor:11', false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (223, 182, 6, 2026, 450186.13, NULL, false);
INSERT INTO budget_line_values (id, line_id, month, year, amount_due, amount_paid, is_overridden) VALUES (781, 182, 7, 2026, 40415.60, NULL, false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (597, 27, 'Travel & Accom', NULL, 0, 'constant', 'constant:1', false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (598, 27, 'Provisional Tax', NULL, 1, 'constant', 'constant:2', false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (599, 27, 'Bank Charges', NULL, 2, 'constant', 'constant:3', false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (629, 27, 'Commission Paid', NULL, 3, 'constant', 'constant:5', false);
INSERT INTO budget_lines (id, section_id, name, notes, sort_order, source, source_key, name_overridden) VALUES (630, 27, 'PAYE', NULL, 4, 'constant', 'constant:6', false);
COMMIT;
